function expr = input_b_uv(t,in2)
%INPUT_B_UV
%    EXPR = INPUT_B_UV(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:54:36

%input_b vector: Crane. Variables structure: [v_theta_1(t); v_r(t); v_beta_2(t); v_beta_1(t); v_Gamma(t); u_theta_1(t); u_r(t); u_beta_2(t); u_beta_1(t); u_Gamma(t); tau_in(t); F_in(t)]
F_in = in2(12,:);
tau_in = in2(11,:);
u_r = in2(7,:);
u_theta_1 = in2(6,:);
t2 = cos(u_theta_1);
expr = [tau_in-F_in.*(t2.*4.46e-2+sin(u_theta_1).*(u_r+2.91647e+1));F_in.*t2;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
end
