function expr = v_uv(t,in2)
%V_UV
%    EXPR = V_UV(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:54:36

%v vector: Crane. Variables structure: [v_theta_1(t); v_r(t); v_beta_2(t); v_beta_1(t); v_Gamma(t); u_theta_1(t); u_r(t); u_beta_2(t); u_beta_1(t); u_Gamma(t)]
v_Gamma = in2(5,:);
v_beta_1 = in2(4,:);
v_beta_2 = in2(3,:);
v_r = in2(2,:);
v_theta_1 = in2(1,:);
expr = [0.0;0.0;0.0;0.0;0.0;v_theta_1;v_r;v_beta_2;v_beta_1;v_Gamma];
end
