function expr = v_function(t,in2)
%V_FUNCTION
%    EXPR = V_FUNCTION(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:44:29

v_theta = in2(1,:);
expr = v_theta;
end
