function expr = d_Virtual_Velocity_Components_uv_Jib_2(t,in2)
%d_Virtual_Velocity_Components_uv_Jib_2
%    EXPR = d_Virtual_Velocity_Components_uv_Jib_2(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    27-Aug-2024 11:50:43

%Virtual Velocity Components: Rigid Body: Jib r(t)
expr = [0.0;0.0;0.0;0.0;0.0;0.0];
end
