function expr = d_Virtual_Velocity_Components_uv_Jib_4(t,in2)
%d_Virtual_Velocity_Components_uv_Jib_4
%    EXPR = d_Virtual_Velocity_Components_uv_Jib_4(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    27-Aug-2024 11:50:44

%Virtual Velocity Components: Rigid Body: Jib beta_1(t)
expr = [0.0;0.0;0.0;0.0;0.0;0.0];
end
