function expr = d_Virtual_Velocity_Components_uv_Trolley_1(t,in2)
%d_Virtual_Velocity_Components_uv_Trolley_1
%    EXPR = d_Virtual_Velocity_Components_uv_Trolley_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    27-Aug-2024 11:50:44

%Virtual Velocity Components: Rigid Body: Trolley theta_1(t)
u_r = in2(7,:);
u_theta_1 = in2(6,:);
v_r = in2(2,:);
v_theta_1 = in2(1,:);
t2 = cos(u_theta_1);
t3 = sin(u_theta_1);
t4 = u_r+2.91647e+1;
expr = [0.0;0.0;0.0;-t3.*v_r+t3.*v_theta_1.*4.46e-2-t2.*t4.*v_theta_1;t2.*v_r-t2.*v_theta_1.*4.46e-2-t3.*t4.*v_theta_1;0.0];
end
