function expr = Virtual_Velocity_Components_uv_Trolley_3(t,in2)
%Virtual_Velocity_Components_uv_Trolley_3
%    EXPR = Virtual_Velocity_Components_uv_Trolley_3(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    27-Aug-2024 11:50:45

%Virtual Velocity Components: Rigid Body: Trolley beta_2(t)
expr = [0.0;0.0;0.0;0.0;0.0;0.0];
end
