function expr = d_Virtual_Velocity_Components_uv_Trolley_6(t,in2)
%d_Virtual_Velocity_Components_uv_Trolley_6
%    EXPR = d_Virtual_Velocity_Components_uv_Trolley_6(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 12:58:18

%Virtual Velocity Components: Rigid Body: Trolley ly(t)
expr = [0.0;0.0;0.0;0.0;0.0;0.0];
end
