function expr = d_Virtual_Velocity_Components_uv_Jib_5(t,in2)
%d_Virtual_Velocity_Components_uv_Jib_5
%    EXPR = d_Virtual_Velocity_Components_uv_Jib_5(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:54:13

%Virtual Velocity Components: Rigid Body: Jib Gamma(t)
expr = [0.0;0.0;0.0;0.0;0.0;0.0];
end
