function expr = d_Virtual_Velocity_Components_uv_Jib_3(t,in2)
%d_Virtual_Velocity_Components_uv_Jib_3
%    EXPR = d_Virtual_Velocity_Components_uv_Jib_3(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:54:13

%Virtual Velocity Components: Rigid Body: Jib beta_2(t)
expr = [0.0;0.0;0.0;0.0;0.0;0.0];
end
