function expr = Virtual_Velocity_Components_uv_Load_6(t,in2)
%Virtual_Velocity_Components_uv_Load_6
%    EXPR = Virtual_Velocity_Components_uv_Load_6(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 12:58:22

%Virtual Velocity Components: Rigid Body: Load ly(t)
u_beta_1 = in2(10,:);
u_beta_2 = in2(9,:);
u_theta_1 = in2(7,:);
t2 = cos(u_beta_1);
t3 = cos(u_theta_1);
t4 = sin(u_beta_1);
t5 = sin(u_beta_2);
t6 = sin(u_theta_1);
expr = [0.0;0.0;0.0;t4.*t6+t2.*t3.*t5;-t3.*t4+t2.*t5.*t6;t2.*cos(u_beta_2)];
end
