function expr = Virtual_Velocity_Components_uv_Trolley_5(t,in2)
%Virtual_Velocity_Components_uv_Trolley_5
%    EXPR = Virtual_Velocity_Components_uv_Trolley_5(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:54:15

%Virtual Velocity Components: Rigid Body: Trolley Gamma(t)
expr = [0.0;0.0;0.0;0.0;0.0;0.0];
end
