function expr = Virtual_Velocity_Components_uv_Trolley_4(t,in2)
%Virtual_Velocity_Components_uv_Trolley_4
%    EXPR = Virtual_Velocity_Components_uv_Trolley_4(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:54:15

%Virtual Velocity Components: Rigid Body: Trolley beta_1(t)
expr = [0.0;0.0;0.0;0.0;0.0;0.0];
end
