function expr = Virtual_Velocity_Components_uv_Jib_2(t,in2)
%Virtual_Velocity_Components_uv_Jib_2
%    EXPR = Virtual_Velocity_Components_uv_Jib_2(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:54:13

%Virtual Velocity Components: Rigid Body: Jib r(t)
expr = [0.0;0.0;0.0;0.0;0.0;0.0];
end
