function expr = Virtual_Velocity_Components_uv_Bar_1(t,in2)
%Virtual_Velocity_Components_uv_Bar_1
%    EXPR = Virtual_Velocity_Components_uv_Bar_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:44:27

%Virtual Velocity Components: Rigid Body: Bar theta(t)
u_theta = in2(2,:);
expr = [1.0;0.0;0.0;0.0;cos(u_theta).*5.0e-1;sin(u_theta).*5.0e-1];
end
