function expr = d_Virtual_Velocity_Components_uv_Bar_2_2(t,in2)
%d_Virtual_Velocity_Components_uv_Bar_2_2
%    EXPR = d_Virtual_Velocity_Components_uv_Bar_2_2(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2024 17:14:58

%Virtual Velocity Components: Rigid Body: Bar_2 theta_2(t)
u_theta_2 = in2(4,:);
v_theta_2 = in2(2,:);
expr = [0.0;0.0;0.0;0.0;-v_theta_2.*sin(u_theta_2);v_theta_2.*cos(u_theta_2)];
end
