function expr = d_Virtual_Velocity_Components_uv_Bar_1_1(t,in2)
%d_Virtual_Velocity_Components_uv_Bar_1_1
%    EXPR = d_Virtual_Velocity_Components_uv_Bar_1_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2024 17:14:57

%Virtual Velocity Components: Rigid Body: Bar_1 theta_1(t)
u_theta_1 = in2(3,:);
v_theta_1 = in2(1,:);
expr = [0.0;0.0;0.0;0.0;-v_theta_1.*sin(u_theta_1);v_theta_1.*cos(u_theta_1)];
end
