function expr = Virtual_Velocity_Components_uv_Jib_1(t,in2)
%Virtual_Velocity_Components_uv_Jib_1
%    EXPR = Virtual_Velocity_Components_uv_Jib_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    21-Jun-2024 21:35:11

%Virtual Velocity Components: Rigid Body: Jib theta_1(t)
u_theta_1 = in2(5,:);
t2 = 2.294640751838945e+4;
expr = [0.0;0.0;1.0;t2.*cos(u_theta_1+atan(3.49117199391172e+1)).*(-1.0e-4);t2.*cos(u_theta_1-atan(2.864367615642848e-2)).*(-1.0e-4);0.0];
end
