function expr = Virtual_Velocity_Components_uv_Bar_1_2(t,in2)
%Virtual_Velocity_Components_uv_Bar_1_2
%    EXPR = Virtual_Velocity_Components_uv_Bar_1_2(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2024 17:14:57

%Virtual Velocity Components: Rigid Body: Bar_1 theta_2(t)
expr = [0.0;0.0;0.0;0.0;0.0;0.0];
end
