function expr = A_uv(t,in2)
%A_uv
%    EXPR = A_uv(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:44:28

%A matrix: Pendulo_Simple. Variables structure: [v_theta(t); u_theta(t)]
expr = reshape([3.333333333333333e-1,0.0,0.0,1.0],[2,2]);
end
