function expr = v_uv(t,in2)
%V_UV
%    EXPR = V_UV(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Aug-2024 17:44:29

%v vector: Pendulo_Simple. Variables structure: [v_theta(t); u_theta(t)]
v_theta = in2(1,:);
expr = [0.0;v_theta];
end
