function expr = input_b_uv(t,in2)
%INPUT_B_UV
%    EXPR = INPUT_B_UV(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    27-Aug-2024 11:51:16

%input_b vector: Crane. Variables structure: [v_theta_1(t); v_r(t); v_beta_2(t); v_beta_1(t); v_Gamma(t); u_theta_1(t); u_r(t); u_beta_2(t); u_beta_1(t); u_Gamma(t); tau_in(t); F_h(t)]
F_h = in2(12,:);
tau_in = in2(11,:);
u_beta_1 = in2(9,:);
u_beta_2 = in2(8,:);
expr = [tau_in;0.0;F_h.*cos(u_beta_1).*sin(u_beta_2).*(7.39e+2./2.5e+2);F_h.*cos(u_beta_2).*sin(u_beta_1).*(7.39e+2./2.5e+2);0.0;0.0;0.0;0.0;0.0;0.0];
end
